version: 2.1

jobs:
  lint:
    docker:
      # Image with Python/Node and therapist pre-installed
      - image: mozilla/cidockerbases:therapist-latest

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run:
          name: Install node dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - "node_modules"
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Lint
          command: therapist run --use-tracked-files

  build-extension:
    docker:
      - image: node:12-stretch

    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run:
          name: Install node dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - "node_modules"
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Build extension
          command: yarn build
      - store_artifacts:
          path: web-ext-artifacts

workflows:
  version: 2
  main:
    jobs:
      - lint
      - build-extension
